version: '3.1'
services:
  stats-server:
    image: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    image: mysql

  ewm-service:
    image: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db

  ewm-db:
    image: mysql