version: '3.1'
services:
  stats-server:
    container_name: stats-server
    build:
      dockerfile: Dockerfile-statsserver
      context: ./stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    container_name: stats-db
    image: mariadb
    ports:
      - "9091:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=stats
      - MARIADB_USER=stats_user
      - MARIADB_PASSWORD=stats_password

  ewm-service:
    container_name: ewm-service
    build:
      dockerfile: Dockerfile-ewmservice
      context: ./ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db

  ewm-db:
    container_name: ewm-db
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=ewmservice
      - MARIADB_USER=ewmservice_user
      - MARIADB_PASSWORD=ewmservice_password