version: '3.1'
services:
  stats-server:
    container_name: stats-server
    build:
      dockerfile: Dockerfile-statsserver
      context: ./stats-server
    ports:
      - "${STATS_SERVER_HOST_PORT}:${STATS_SERVER_CONTAINER_PORT}"
    depends_on:
      - stats-db

  stats-db:
    container_name: stats-db
    image: mariadb
    ports:
      - "${STATS_DB_HOST_PORT}:${STATS_DB_CONTAINER_PORT}"
    environment:
      MARIADB_ROOT_PASSWORD: "${STATS_DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${STATS_DB_DATABASE_NAME}"
      MARIADB_USER: "${STATS_DB_USER}"
      MARIADB_PASSWORD: "${STATS_DB_PASSWORD}"

  ewm-service:
    container_name: ewm-service
    build:
      dockerfile: Dockerfile-ewmservice
      context: ./ewm-service
    ports:
      - "${EWM_SERVICE_HOST_PORT}:${EWM_SERVICE_CONTAINER_PORT}"
    depends_on:
      - ewm-db

  ewm-db:
    container_name: ewm-db
    image: mariadb
    ports:
      - "${EWM_DB_HOST_PORT}:${EWM_DB_CONTAINER_PORT}"
    environment:
      MARIADB_ROOT_PASSWORD: "${EWM_DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${EWM_DB_DATABASE_NAME}"
      MARIADB_USER: "${EWM_DB_USER}"
      MARIADB_PASSWORD: "${EWM_DB_PASSWORD}"