version: '3.1'
services:
  stats-server:
    image: stats-server
    ports:
      - "${STATS_SERVER_HOST_PORT}:${STATS_SERVER_CONTAINER_PORT}"
    depends_on:
      - stats-db

  stats-db:
    image: mysql
    environment:
      MARIADB_ROOT_PASSWORD: "${STATS_DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${STATS_DB_DATABASE_NAME}"
      MARIADB_USER: "${STATS_DB_USER}"
      MARIADB_PASSWORD: "${STATS_DB_PASSWORD}"

  ewm-service:
    image: ewm-service
    ports:
      - "${EWM_SERVICE_HOST_PORT}:${EWM_SERVICE_CONTAINER_PORT}"
    depends_on:
      - ewm-db

  ewm-db:
    image: mysql
    environment:
      MARIADB_ROOT_PASSWORD: "${EWM_DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${EWM_DB_DATABASE_NAME}"
      MARIADB_USER: "${EWM_DB_USER}"
      MARIADB_PASSWORD: "${EWM_DB_PASSWORD}"