version: '3.1'
services:
  stats-server:
    container_name: stats-server
    build:
      dockerfile: Dockerfile-statsserver
      context: ./stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    container_name: stats-db
    image: postgres
    ports:
      - "9091:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=stats_password

  ewm-service:
    container_name: ewm-service
    build:
      dockerfile: Dockerfile-ewmservice
      context: ./ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db

  ewm-db:
    container_name: ewm-db
    image: postgres
    ports:
      - "8081:5432"
    environment:
      - POSTGRES_DB=ewmservice
      - POSTGRES_USER=ewmservice_user
      - POSTGRES_PASSWORD=ewmservice_password
    depends_on:
      - stats-db