version: '3.1'
services:
  stats-server:
    container_name: stats-server
    build:
      dockerfile: Dockerfile-statsserver
      context: ./stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    container_name: stats-db
    image: mariadb:10.5
    ports:
      - "9091:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=stats
      - MARIADB_USER=stats_user
      - MARIADB_PASSWORD=stats_password
    healthcheck:
      test: [ "CMD", "mysql", "-u", "stats_user", "-h", "stats-db", "-pstats_password", "stats"]
      timeout: 45s
      interval: 10s
      retries: 10

  ewm-service:
    container_name: ewm-service
    build:
      dockerfile: Dockerfile-ewmservice
      context: ./ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db

  ewm-db:
    container_name: ewm-db
    image: mariadb:10.5
    ports:
      - "8081:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=ewmservice
      - MARIADB_USER=ewmservice_user
      - MARIADB_PASSWORD=ewmservice_password
    healthcheck:
      test: [ "CMD", "mysql", "-u", "ewmservice_user", "-h", "ewm-db", "-pewmservice_password", "ewmservice"]
      timeout: 45s
      interval: 10s
      retries: 10